### ISSUE TITLE
[BUG] expfit model for dry rock's pressure adjustment does not work

### ISSUE THREAD

**Issue by JiZur** [equinor/open_petro_elastic#10]
Using the following input data 1_input_data.csv: 
[1_input_data.csv](https://github.com/equinor/open_petro_elastic/files/7089160/1_input_data.csv)

I used the following PEM config:

```
dry_rock:
  adjustments:
  - model:
      coefficients:
        density:
        - 1
        - 0
        - 1
        primary_velocity:
        - 1
        - -0.3
        - -11000000.0
        secondary_velocity:
        - 1
        - -0.25
        - -7500000.0
      type: expfit
    type: pressure_dependency
  model:
    coefficients:
      bulk_modulus:
      - - 8120000000
        - -3040000000
        - 0
        - 0
        - 0
      shear_modulus:
      - - 8160000000
        - -1250000000
        - 0
        - 0
        - 0
    type: polyfit
  porosity:
    column: PORO
fluids:
  constituents:
  - fraction:
      column: SWAT
    material:
      salinity: 48355
      type: brine
  - material:
      gas_gravity: 0.591
      gas_oil_ratio:
        column: RS
      reference_density:
        column: OIL_DEN
      type: oil
  - fraction:
      column: SGAS
    material:
      gas_gravity: 0.5913
      type: gas
  fluid_model: flag
  mix_method: wood
  temperature:
    column: TEMP
minerals:
  constituents:
  - fraction:
      column: FSAND
    material:
      bulk_modulus: 36800000000.0
      density: 2650
      shear_modulus: 44000000000.0
  - material:
      bulk_modulus: 26000000000.0
      density: 2650
      shear_modulus: 20000000000.0
pressure:
  fluid:
    column: PRESSURE
  max_effective: 100000000
  overburden: 46000000
  reference:
    column: PRES_REF
```

with the following Python script to run it:

```
#! /usr/bin/env python
"""
This script executes Petro-Elastic Modelling using the petro_elastic library
available on Komodo

Author: Jimmy Zurcher (jiz@equinor.com), November 2020
"""
import pandas as pd
import numpy as np
import open_petro_elastic as pem
from open_petro_elastic.__main__ import make_input


SEISDATES = ['01012020']

PROPS_DATE_NAME = ["PRESSURE", "RS", "SWAT", "SGAS","OIL_DEN"]

PEM_CSV = "../../sim2seis/input/pem/1_input_data.csv"

PEM_CONFIG_FILE = "../../sim2seis/model/pem/pem_config.yml"


RUN_ID = ""

def run_pem():
    #import pdb; pdb.set_trace()
    for date in SEISDATES:
        print(date)
        date = str(date).replace("-", "")

        # INPUTS - using generic names for dynamic properties
        df = pd.read_csv(PEM_CSV)
        for pname in PROPS_DATE_NAME:
            df[pname] = df[pname+"_"+date]
        df.to_csv(PEM_CSV, index=False)

        with open(PEM_CONFIG_FILE, 'r') as f:
            pem_input = make_input(f, PEM_CSV)

        # PEM CALCULATION
        print(">> PEM calculation")
        pressure = pem_input.pressure
        mixed_mineral = pem_input.minerals.as_mixture
        mixed_fluid = pem_input.fluids.as_mixture(pressure)
        dry_rock_material = pem_input.dry_rock.material(mixed_mineral, pressure)
        dense_packing = pem_input.dry_rock.nonporous(mixed_mineral)
        saturated_rock = pem.material.fluid_substitution(
            dry_rock_material,
            dense_packing,
            mixed_fluid,
            pem_input.dry_rock.porosity,
        )

        # OUTPUTS
        vp = saturated_rock.primary_velocity
        vs = saturated_rock.secondary_velocity
        df["VP_"+date+RUN_ID] = vp
        df["VS_"+date+RUN_ID] = vs
        df["AI_"+date+RUN_ID] = saturated_rock.acoustic_impedance
        df["SI_"+date+RUN_ID] = saturated_rock.shear_impedance
        df["DENS_"+date+RUN_ID] = saturated_rock.density
        df["VPVS_"+date+RUN_ID] = vp / vs

        # Compute dT properties (used for TWT properties)
        dz = df["dZ"]
        dtpp = 2000.0 * dz / vp
        dtss = 2000.0 * dz / vs
        dtps = (dtpp + dtss) / 2.0

        df["DTPP_"+date+RUN_ID] = dtpp
        df["DTSS_"+date+RUN_ID] = dtss
        df["DTPS_"+date+RUN_ID] = dtps

        df.to_csv(PEM_CSV, index=False)


if __name__ == "__main__":
    run_pem()
    print("done.")
```

The expfit model (dry rock pressure adjustment) does not work due to overflow issue and the created outputs are empty. The code works fine if I remove the pressure adjustment part. The coefficients expressed as `coeff[:,i]` while we only have a flat list of coefficients `coeff[i]` might be the cause. I might also be a bit superfluous as user never define them as 2D array but a simple list of c0, c1, c2 coefficients for the expfit model (`factor = c0 + c1 * exp(pressure / c3)`)

**Comment by eivindjahren** [comment]
@JiZur The problem seems to be that the saturated rock is giving all `nan` values. I think that is related to the overflow. I am having a look at it now.

**Comment by eivindjahren** [comment]
The problem seems to be that we are missing a transpose here. In the model the coefficients are
```
[[ 1.0e+00  0.0e+00  1.0e+00]
 [ 1.0e+00 -3.0e-01 -1.1e+07]
 [ 1.0e+00 -2.5e-01 -7.5e+06]]
 ```
 And the pressure is: 
 ```
  pressure=[2.6e7 2.59e7 2.59e7 2.58e7 2.57e7]
```
So the expected values for density of the first row is `1.0 *  + 0 * exp(2.6e7 / 1.0)`. However, because the dimension is incorrect, we get `1.0 + 1.0 * exp(2.6e7/1.0)` which becomes NaN as exp overflows. I am still trying to figure out what is going on with that as we seem to get the correct shape other places.

**Comment by eivindjahren** [comment]
The problem is the overflow in the `density` value. Overflow results in a `NaN` value and since `0.0 * np.nan == np.nan` the density remains `np.nan` although we would expect a `0.0` here. The easy fix is to change the config to 
```
  adjustments:
  - model:
      coefficients:
        density:
        - 1
        - 0
        - 10000000
...
```

so that the exp function does not overflow. It is a general problem with the expfit model that the third parameter should not get too large. I think perhaps what we should do here is to catch the warning emitted by `exp`, and provide some guidance in case of overflow.
