### ISSUE TITLE
Error while mixing inputs as constant and vectors for fluid constituent fractions (saturations)

### ISSUE THREAD

**Issue by JiZur** [equinor/open_petro_elastic#14]
Using the following config file:
```
dry_rock:
  adjustments:
  - coefficients:
      density:
      - - 0.0
        - 0.0
      - - 1.0
        - 0.0
      primary_velocity:
      - - 0.0
        - 5.4
      - - 1.0
        - 0.0
      secondary_velocity:
      - - 0.0
        - 1.86
      - - 1.0
        - 0.0
    depth:
      column: DEPTH
    max_depth: 3000.0
    reference_depth: 1500.0
    type: depth_trend
  - model:
      type: patchy_cement
      cement:
        bulk_modulus: 76800000000.0
        density: 2710.0
        shear_modulus: 32000000000.0
      cement_fraction: 0.05
      shear_reduction: 0.1
      critical_porosity: 0.5
    type: pressure_dependency
  model:
    coefficients:
      primary_velocity:
      - - 4173
        - -4913
        - 0
        - 0
        - 0
      secondary_velocity:
      - - 2402
        - -3324
        - 0
        - 0
        - 0
    type: polyfit
  porosity:
    column: PORO
fluids:
  constituents:
  - fraction:
      column: SWAT
    material:
      salinity: 54500
      type: brine
  - fraction: 0.1
    material:
      gas_gravity: 0.574
      gas_oil_ratio:
        column: RS
      reference_density: 969
      type: oil
  - fraction:
      column: SGAS
    material:
      gas_gravity: 0.574
      type: gas
  - fluid_model: span_wagner
    material:
      interpolate_density: true
      type: carbon_dioxide
  mix_method: wood
  temperature: 46
minerals:
  constituents:
  - fraction:
      column: FSAND
    material:
      bulk_modulus: 36800000000.0
      density: 2650
      shear_modulus: 44000000000.0
  - material:
      bulk_modulus: 50000000000.0
      density: 2680
      shear_modulus: 20000000000.0
pressure:
  fluid:
    column: PRESSURE
  max_effective: 100000000
  overburden:
    column: PRES_OVER
  reference:
    column: PRES_REF
```
I got the following error message:
![image](https://user-images.githubusercontent.com/40593100/144219574-d80a9589-b5db-4d0f-9fd3-4597ab7c975f.png)

I seems that the vectorization is not done properly with this setup mixing constant saturation and vector saturation (see the Deprecated Warning at the beginning of the screenshot and the fact that the np.any() command seems not to be effective)
